### ISSUE TITLE
jetsonimageのチェックサムの整合が取れていない

### ISSUE THREAD

**Issue by swiftfile** [OUXT-Polaris/ouxt_automation#201]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - ROS Distro: [e.g. galactic]

**Additional context**

**Comment by swiftfile** [comment]
Yes, it's URL.
Sorry for the lack of information on this issue.
Thanks.

**Comment by hakuturu583** [comment]
This problem was fixed in #214
